[build]
  publish = "dist"
  command = "npm run build"

[dev]
  publish = "./dist"
  command = "npm run serve"

[[plugins]]
  # package = "./node_modules/@netlify/demo-restaurant-sites-data/plugins/{PLUGIN_DIRECTORY}"
  package = "./node_modules/@netlify/demo-restaurant-sites-data/plugins/contentful"

  [plugins.inputs]
    # Directory for the generated JSON data files to reside in
    dataDir = "src/site/_data"